# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    sources.mk                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kiroussa <oss@xtrm.me>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/18 14:21:11 by kiroussa          #+#    #+#              #
#    Updated: 2024/11/18 00:50:49 by kiroussa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC_FILES		=  	\
					data/hashmap/ft_map_clear.c \
					data/hashmap/ft_map_contains.c \
					data/hashmap/ft_map_free.c \
					data/hashmap/ft_map_get.c \
					data/hashmap/ft_map_keys.c \
					data/hashmap/ft_map_new.c \
					data/hashmap/ft_map_put.c \
					data/hashmap/ft_map_remove.c \
					data/hashmap/ft_map_size.c \
					data/list/ft_lst_add.c \
					data/list/ft_lst_clone.c \
				   	data/list/ft_lst_insert.c \
				   	data/list/ft_lst_free.c \
					data/list/ft_lst_get.c \
				   	data/list/ft_lst_delete.c \
				   	data/list/ft_lst_foreach.c \
				   	data/list/ft_lst_last.c \
				   	data/list/ft_lst_map.c \
				   	data/list/ft_lst_new.c \
					data/list/ft_lst_remove.c \
					data/list/ft_lst_size.c \
					data/list/ft_lst_tadd.c \
					data/list/ft_lst_tget.c \
					data/list/ft_lst_tinsert.c \
					data/list/ft_lst_tlast.c \
					getopt/long/ft_opt_get_long.c \
					getopt/long/ft_opt_get_long_core.c \
					getopt/posix/ft_opt_get_posix.c \
					getopt/ft_opt_args.c \
					getopt/ft_opt_get.c \
					getopt/ft_opt_globals.c \
					getopt/ft_opt_msg.c \
					getopt/ft_opt_permute.c \
					getopt/ft_opt_reset.c \
					io/ft_closep.c \
				   	io/get_next_line.c \
					math/mat3d/m3d.c \
					math/mat3d/m3d_det.c \
					math/mat3d/m3d_identity.c \
					math/mat3d/m3d_inv.c \
					math/mat3d/m3d_mult.c \
					math/mat3d/m3d_mult_v3d.c \
					math/mat3d/m3d_rot.c \
					math/mat3d/m3d_rot_v3d.c \
					math/mat3d/m3d_rot_x.c \
					math/mat3d/m3d_rot_y.c \
					math/mat3d/m3d_rot_z.c \
					math/mat3d/m3d_scale.c \
					math/mat3d/m3d_solv.c \
					math/vec2i/v2i.c \
					math/vec2i/v2i_eq.c \
					math/vec3d/v3d.c \
					math/vec3d/v3d_abs.c \
					math/vec3d/v3d_add.c \
					math/vec3d/v3d_addmult.c \
					math/vec3d/v3d_cross.c \
					math/vec3d/v3d_div.c \
					math/vec3d/v3d_dot.c \
					math/vec3d/v3d_eq.c \
					math/vec3d/v3d_inv.c \
					math/vec3d/v3d_len.c \
					math/vec3d/v3d_lensub.c \
					math/vec3d/v3d_max.c \
					math/vec3d/v3d_min.c \
					math/vec3d/v3d_mult.c \
					math/vec3d/v3d_mult_m3d.c \
					math/vec3d/v3d_mult_v3d.c \
					math/vec3d/v3d_norm.c \
					math/vec3d/v3d_normsub.c \
					math/vec3d/v3d_opp.c \
					math/vec3d/v3d_quadr.c \
					math/vec3d/v3d_sub.c \
					math/vec3d/v3d_to_v2i.c \
					math/ft_abs.c \
					math/ft_fabs.c \
					math/ft_fmax.c \
					math/ft_fmin.c \
					math/ft_fpow.c \
					math/ft_fsign.c \
					math/ft_max.c \
					math/ft_min.c \
					math/ft_pow.c \
					math/ft_sign.c \
					math/ft_sincos.c \
					math/ft_sqrt.c \
					mem/arena/ft_arena_alloc.c \
					mem/arena/ft_arena_clear.c \
					mem/arena/ft_arena_free.c \
					mem/arena/ft_arena_new.c \
				   	mem/ft_bzero.c \
				   	mem/ft_calloc.c \
					mem/ft_freep.c \
				   	mem/ft_memchr.c \
				   	mem/ft_memcmp.c \
				   	mem/ft_memcpy.c \
				   	mem/ft_memmove.c \
				   	mem/ft_memset.c \
					mem/ft_realloc.c \
					print/printf/flag/pf_hash_mutator.c \
					print/printf/flag/pf_leftjustify_mutator.c \
					print/printf/flag/pf_padding_mutator.c \
					print/printf/flag/pf_precision_mutator.c \
					print/printf/str/pf_str_append.c \
					print/printf/str/pf_str_create.c \
					print/printf/str/pf_str_init.c \
					print/printf/type/pf_format_char.c \
					print/printf/type/pf_format_float.c \
					print/printf/type/pf_format_hex.c \
					print/printf/type/pf_format_int.c \
					print/printf/type/pf_format_lenptr.c \
					print/printf/type/pf_format_percent.c \
					print/printf/type/pf_format_pointer.c \
					print/printf/type/pf_format_strerror.c \
					print/printf/type/pf_format_string.c \
					print/printf/type/pf_format_uint.c \
					print/printf/utils/pf_append.c \
					print/printf/utils/pf_prepend_sign.c \
					print/printf/utils/pf_strnjoin.c \
					print/printf/wrapper/ft_asprintf.c \
					print/printf/wrapper/ft_dprintf.c \
					print/printf/wrapper/ft_format.c \
					print/printf/wrapper/ft_printf.c \
					print/printf/wrapper/ft_vdprintf.c \
					print/printf/wrapper/ft_vformat.c \
					print/printf/wrapper/ft_vprintf.c \
					print/printf/ft_vasprintf.c \
					print/printf/pf_format_spec.c \
					print/printf/pf_free_spec.c \
					print/printf/pf_parse_spec.c \
					print/ft_putchar.c \
					print/ft_putchar_fd.c \
				   	print/ft_putendl.c \
				   	print/ft_putendl_fd.c \
				   	print/ft_putnbr.c \
				   	print/ft_putnbr_fd.c \
				   	print/ft_putstr.c \
				   	print/ft_putstr_fd.c \
					string/atox/ft_atof.c \
					string/atox/ft_atoi.c \
					string/atox/ft_atoi_base.c \
					string/atox/ft_atoll.c \
					string/atox/ft_atoui.c \
					string/atox/ft_atoull.c \
					string/compare/ft_isalnum.c \
					string/compare/ft_isalpha.c \
					string/compare/ft_isascii.c \
					string/compare/ft_iscntrl.c \
					string/compare/ft_isdigit.c \
					string/compare/ft_islower.c \
					string/compare/ft_isprint.c \
					string/compare/ft_isspace.c \
					string/compare/ft_isupper.c \
					string/compare/ft_strcmp.c \
					string/compare/ft_strncmp.c \
					string/create/ft_ctostr.c \
					string/create/ft_split.c \
					string/create/ft_splits.c \
					string/create/ft_strdup.c \
					string/create/ft_strdup_range.c \
					string/create/ft_strjoin.c \
					string/create/ft_strjoins.c \
					string/create/ft_strmapi.c \
					string/create/ft_strndup.c \
					string/create/ft_strnew.c \
					string/create/ft_strtrim.c \
					string/create/ft_substr.c \
					string/mutate/ft_stpcpy.c \
					string/mutate/ft_strcat.c \
					string/mutate/ft_strcpy.c \
					string/mutate/ft_strlcat.c \
					string/mutate/ft_strlcpy.c \
					string/mutate/ft_strncat.c \
					string/mutate/ft_strncpy.c \
					string/mutate/ft_strtolower.c \
					string/mutate/ft_strtoupper.c \
					string/mutate/ft_tolower.c \
					string/mutate/ft_toupper.c \
					string/query/ft_lllen.c \
					string/query/ft_lllen_base.c \
					string/query/ft_strall.c \
					string/query/ft_strany.c \
					string/query/ft_strchr.c \
					string/query/ft_strcspn.c \
					string/query/ft_striteri.c \
					string/query/ft_strlen.c \
					string/query/ft_strnstr.c \
					string/query/ft_strpbrk.c \
					string/query/ft_strrchr.c \
					string/query/ft_strspn.c \
					string/query/ft_strstr.c \
					string/query/ft_ulllen.c \
					string/query/ft_ulllen_base.c \
					string/strtox/ft_strtoi.c \
					string/strtox/ft_strtoi_base.c \
					string/strtox/ft_strtoll.c \
					string/xtoa/ft_lltoa.c \
					string/xtoa/ft_lltoa_base.c \
					string/xtoa/ft_ulltoa.c \
					string/xtoa/ft_ulltoa_base.c \
					string/ft_strdel.c \
					wchar/internal/ft_bittab.c \
					wchar/internal/ft_bittab_ranges.c \
					wchar/internal/ft_codeunit.c \
					wchar/internal/ft_illegal_sequence.c \
					wchar/internal/ft_wchar_oob.c \
					wchar/ft_mblen.c \
					wchar/ft_mbtowc.c

